[theme]
primaryColor = "#087F5B"
backgroundColor = "#F4F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14213D"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
